--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archecker-deployment
  namespace: development
  labels:
    app: archecker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archecker
  template:
    metadata:
      labels:
        app: archecker
    spec:
      containers:
      - name: archecker-container
        image: gcr.io/heptio-images/ks-guestbook-demo:0.2 #registry.lts.harvard.edu/lts/archivesspace-checker-dev:sandbox
        ports:
        - containerPort: 80 #9292 
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: archecker-ui
spec:
  type: NodePort
  ports:
  - port: 80 #9292
    targetPort: 80 #9292
    nodePort: 30001 
  selector:
    app: archecker
