--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archecker-deployment
  namespace: development
  labels:
    app: archecker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archecker
  template:
    metadata:
      labels:
        app: archecker
    spec:
      containers:
      - name: archecker-container
        image: registry.lts.harvard.edu/lts/archivesspace-checker-dev:latest
        ports:
        - containerPort: 9292
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: archecker-ui
spec:
  type: NodePort
  ports:
  - port: 9292
    targetPort: 9292
    nodePort: 30001 
  selector:
    app: archecker
