--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: archecker-container
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: archecker-container
  template:
    metadata:
      labels:
        app: archecker-container
    spec:
      containers:
      - image: registry.lts.harvard.edu/lts/archivesspace-checker-dev:sandbox
        name: archecker-container
        ports:
        - containerPort: 9292

---

apiVersion: v1
kind: Service
metadata:
  name: archecker-container
spec:
  type: NodePort
  ports:
  - port: 9292
    targetPort: 9292
    nodePort: 30003
  selector:
    app: archecker-container
